apiVersion : apps/v1
kind: Deployment
metadata:
  name: contacts 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: contacts 
    spec:
      containers:
        - name: contacts 
          image: pkvcontainerregistry.azurecr.io/contacts
          ports:
          - containerPort: 80
